PR #87568: Fix build error on s390x due to missing hwloc headers
Imported from GitHub PR https://github.com/tensorflow/tensorflow/pull/87568

This PR fixes below error on s390x by including required methods from `topology-linux.c`:
```
error: undefined reference to 'hwloc_linux_component'
```

Copybara import of the project:

--
7db6852584c8ccdee357c9468f81ebb9a580871c by namrata-ibm <Namrata.Bhave@ibm.com>:

Fix build error on s390x due to missing hwloc headers

Merging this change closes #87568

PiperOrigin-RevId: 729477754