Unbreak JAX build after TSL/streamexecutor dso_loader changes.
One of the recent TSL changes was causing errors like:
ImportError: /usr/local/google/home/phawkins/.pyenv/versions/3.11.0rc2/envs/py3110rc2/lib/python3.11/site-packages/jaxlib/cuda/_prng.so: undefined symbol: _ZN3tsl3Env7DefaultEv

I believe this happens because JAX was previously getting the Env implementation via a transitive dependency that has now been broken. Unlike TensorFlow, JAX builds all libraries in a "static" configuration.

PiperOrigin-RevId: 483565871